---
- name: Check installation
  command: rvm current
  register: rvm_installed
  changed_when: rvm_installed is failed
  ignore_errors: true

- name: Download installer
  get_url:
    url: https://get.rvm.io
    dest: "{{ rvm_installer_script }}"
    mode: u+rwx
  when: rvm_installed is failed

- name: Check install script
  stat:
    path: "{{ rvm_installer_script }}"
  register: stat_install_rvm

- name: Install rvm
  command: "{{ rvm_installer_script }} stable --auto-dotfiles"
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.rvm"
  register: rvm_install_result
  when: stat_install_rvm.stat.exists

- name: Set shell config file variable
  set_fact:
    shell_config_file: "{{ ansible_distribution_version is version(10.15, '<') | ternary ('.bashrc', '.zshrc') }}"

- name: Check shell config file exists
  stat:
    path: "{{ ansible_env.HOME }}/{{ shell_config_file }}"
  register: shell_config_file_stat

- name: Create shell config file
  file:
    path: "{{ ansible_env.HOME }}/{{ shell_config_file }}"
    state: touch
    mode: u+rw
  when: not ansible_check_mode
  changed_when: shell_config_file_stat.stat is defined and not shell_config_file_stat.stat.exists

- name: Run post install script
  shell: "source {{ ansible_env.HOME }}/{{ shell_config_file }} && {{ ansible_env.HOME }}/.rvm/scripts/rvm"
  args:
    executable: "{{ ansible_env.SHELL }}"
  when:
    - rvm_install_result.rc is defined and rvm_install_result.rc == 0
    - not ansible_check_mode

- name: Update rvm
  command: rvm get head
  changed_when: False
  when:
    - rvm_install_result.rc is defined and rvm_install_result.rc == 0
    - not ansible_check_mode

- name: Configure rvm
  command: rvm autolibs enable
  changed_when: False
  when: not ansible_check_mode
